// user
export const GET_ABOUT_USER_SUCCESS: 'GET_ABOUT_USER_SUCCESS' =
  'GET_ABOUT_USER_SUCCESS';
export const GET_ABOUT_USER_REQUEST: 'GET_ABOUT_USER_REQUEST' =
  'GET_ABOUT_USER_REQUEST';
export const GET_ABOUT_USER_FAILED: 'GET_ABOUT_USER_FAILED' =
  'GET_ABOUT_USER_FAILED';

export const POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS' =
  'POST_REGISTER_SUCCESS';
export const POST_REGISTER_REQUEST: 'POST_REGISTER_REQUEST' =
  'POST_REGISTER_REQUEST';
export const POST_REGISTER_FAILED: 'POST_REGISTER_FAILED' =
  'POST_REGISTER_FAILED';
export const SET_AUTH_LOGGED_IN = 'SET_AUTH_LOGGED_IN';

export const POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST' = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_FAILED: 'POST_LOGIN_FAILED' = 'POST_LOGIN_FAILED';

export const SET_USER_DATA: 'SET_USER_DATA' = 'SET_USER_DATA';

export const POST_REFRESH_TOKEN_SUCCESS: 'POST_REFRESH_TOKEN_SUCCESS' =
  'POST_REFRESH_TOKEN_SUCCESS';
export const POST_REFRESH_TOKEN_REQUEST: 'POST_REFRESH_TOKEN_REQUEST' =
  'POST_REFRESH_TOKEN_REQUEST';
export const POST_REFRESH_TOKEN_FAILED: 'POST_REFRESH_TOKEN_FAILED' =
  'POST_REFRESH_TOKEN_FAILED';

export const POST_LOGOUT_SUCCESS: 'POST_LOGOUT_SUCCESS' = 'POST_LOGOUT_SUCCESS';
export const POST_LOGOUT_REQUEST: 'POST_LOGOUT_REQUEST' = 'POST_LOGOUT_REQUEST';
export const POST_LOGOUT_FAILED: 'POST_LOGOUT_FAILED' = 'POST_LOGOUT_FAILED';

// room
export const SET_ROOM_DATA: 'SET_ROOM_DATA' = 'SET_ROOM_DATA';
export const SET_SIZE_WALS: 'SET_SIZE_WALS' = 'SET_SIZE_WALS';

export const ADD_ROOM_DATA: 'ADD_ROOM_DATA' = 'ADD_ROOM_DATA';

export const ADD_ELEMENT_ROOM: 'ADD_ELEMENT_ROOM' = 'ADD_ELEMENT_ROOM';
export const DELETE_ELEMENT_ROOM: 'DELETE_ELEMENT_ROOM' = 'DELETE_ELEMENT_ROOM';
export const UPDATE_ELEMENT_ROOM: 'UPDATE_ELEMENT_ROOM' = 'UPDATE_ELEMENT_ROOM';
export const ELEMENTS_DATA: 'ELEMENTS_DATA' = 'ELEMENTS_DATA';
export const ELEMENTS_DATA_BULK: 'ELEMENTS_DATA_BULK' = 'ELEMENTS_DATA_BULK';
export const EDIT_ELEMENT: 'EDIT_ELEMENT' = 'EDIT_ELEMENT';
export const UPDATE_ROOM_DATA: 'UPDATE_ROOM_DATA' = 'UPDATE_ROOM_DATA';
export const DATA_OBJ: 'DATA_OBJ' = 'DATA_OBJ';

export const GET_ROOM_REQUEST: 'GET_ROOM_REQUEST' = 'GET_ROOM_REQUEST';
export const GET_ROOM_SUCCESS: 'GET_ROOM_SUCCESS' = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAILED: 'GET_ROOM_FAILED' = 'GET_ROOM_FAILED';

export const POST_ADD_ROOM_REQUEST: 'POST_ADD_ROOM_REQUEST' =
  'POST_ADD_ROOM_REQUEST';
export const POST_ADD_ROOM_SUCCESS: 'POST_ADD_ROOM_SUCCESS' =
  'POST_ADD_ROOM_SUCCESS';
export const POST_ADD_ROOM_FAILED: 'POST_ADD_ROOM_FAILED' =
  'POST_ADD_ROOM_FAILED';

export const PATCH_ROOM_REQUEST: 'PATCH_ROOM_REQUEST' = 'PATCH_ROOM_REQUEST';
export const PATCH_ROOM_SUCCESS: 'PATCH_ROOM_SUCCESS' = 'PATCH_ROOM_SUCCESS';
export const PATCH_ROOM_FAILED: 'PATCH_ROOM_FAILED' = 'PATCH_ROOM_FAILED';

export const ADD_OR_UPDATE_ROOM: 'ADD_OR_UPDATE_ROOM' = 'ADD_OR_UPDATE_ROOM';

export const NOTIFICATION_SAVE_ROOM: 'NOTIFICATION_SAVE_ROOM' =
  'NOTIFICATION_SAVE_ROOM';

export const UPDATE_LAST_DRAWING_WALLS: 'UPDATE_LAST_DRAWING_WALLS' =
  'UPDATE_LAST_DRAWING_WALLS';

export const UPDATE_SIZE_WALLS: 'UPDATE_SIZE_WALLS' = 'UPDATE_SIZE_WALLS';

export const PATHS: 'PATHS' = 'PATHS';
export const POINTS: 'POINTS' = 'POINTS';
export const CLEAR_PATHS: 'CLEAR_PATHS' = 'CLEAR_PATHS';
export const CLEAR_POINTS: 'CLEAR_POINTS' = 'CLEAR_POINTS';
export const RESET_CURRENT_DRAWING: 'RESET_CURRENT_DRAWING' =
  'RESET_CURRENT_DRAWING';
export const SET_COUNT_WALL_DRAW: 'SET_COUNT_WALL_DRAW' = 'SET_COUNT_WALL_DRAW';
export const WALLS_DATA: 'WALLS_DATA' = 'WALLS_DATA';

export const SET_CURRENT_PATH: 'SET_CURRENT_PATH' = 'SET_CURRENT_PATH';
export const ADD_TO_CURRENT_PATH: 'ADD_TO_CURRENT_PATH' = 'ADD_TO_CURRENT_PATH';
export const SET_LAST_POINT: 'SET_LAST_POINT' = 'SET_LAST_POINT';

export const SET_MODAL_VISIBLE_BACK_LIGHT: 'SET_MODAL_VISIBLE_BACK_LIGHT' =
  'SET_MODAL_VISIBLE_BACK_LIGHT';
export const SET_MODAL_VISIBLE: 'SET_MODAL_VISIBLE' = 'SET_MODAL_VISIBLE';

export const SET_ELEMENTS_WALL_MODAL_VISIBLE: 'SET_ELEMENTS_WALL_MODAL_VISIBLE' =
  'SET_ELEMENTS_WALL_MODAL_VISIBLE';
export const SET_IS_VISIBLE_EDIT_MODAL: 'SET_IS_VISIBLE_EDIT_MODAL' =
  'SET_IS_VISIBLE_EDIT_MODAL';

export const SET_ELEMENT_MODAL_VISIBLE: 'SET_ELEMENT_MODAL_VISIBLE' =
  'SET_ELEMENT_MODAL_VISIBLE';

export const SET_OPEN_FORM_DATA_SIZE: 'SET_OPEN_FORM_DATA_SIZE' =
  'SET_OPEN_FORM_DATA_SIZE';

export const SET_SELECTED_LINE: 'SET_SELECTED_LINE' = 'SET_SELECTED_LINE';

export const SET_IS_STYLE_LINE: 'SET_IS_STYLE_LINE' = 'SET_IS_STYLE_LINE';

export const SET_ACTIVE_WALL_INDEX: 'SET_ACTIVE_WALL_INDEX' =
  'SET_ACTIVE_WALL_INDEX';

export const SET_UPDATE_STROKE_DASHARRAYS: 'SET_UPDATE_STROKE_DASHARRAYS' =
  'SET_UPDATE_STROKE_DASHARRAYS';
export const RESET_LINE_DASHARRAYS: 'RESET_LINE_DASHARRAYS' =
  'RESET_LINE_DASHARRAYS';
export const CURRENT_LINE_DASHARRAYS: 'CURRENT_LINE_DASHARRAYS' =
  'CURRENT_LINE_DASHARRAYS';

export const SET_DATA_EDIT_WALL: 'SET_DATA_EDIT_WALL' = 'SET_DATA_EDIT_WALL';
