export const GET_ABOUT_USER_SUCCESS: 'GET_ABOUT_USER_SUCCESS' =
  'GET_ABOUT_USER_SUCCESS';
export const GET_ABOUT_USER_REQUEST: 'GET_ABOUT_USER_REQUEST' =
  'GET_ABOUT_USER_REQUEST';
export const GET_ABOUT_USER_FAILED: 'GET_ABOUT_USER_FAILED' =
  'GET_ABOUT_USER_FAILED';

export const POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS' =
  'POST_REGISTER_SUCCESS';
export const POST_REGISTER_REQUEST: 'POST_REGISTER_REQUEST' =
  'POST_REGISTER_REQUEST';
export const POST_REGISTER_FAILED: 'POST_REGISTER_FAILED' =
  'POST_REGISTER_FAILED';
export const SET_AUTH_LOGGED_IN = 'SET_AUTH_LOGGED_IN';

export const POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST' = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_FAILED: 'POST_LOGIN_FAILED' = 'POST_LOGIN_FAILED';

export const SET_USER_DATA: 'SET_USER_DATA' = 'SET_USER_DATA';

export const POST_REFRESH_TOKEN_SUCCESS: 'POST_REFRESH_TOKEN_SUCCESS' =
  'POST_REFRESH_TOKEN_SUCCESS';
export const POST_REFRESH_TOKEN_REQUEST: 'POST_REFRESH_TOKEN_REQUEST' =
  'POST_REFRESH_TOKEN_REQUEST';
export const POST_REFRESH_TOKEN_FAILED: 'POST_REFRESH_TOKEN_FAILED' =
  'POST_REFRESH_TOKEN_FAILED';

export const POST_LOGOUT_SUCCESS: 'POST_LOGOUT_SUCCESS' = 'POST_LOGOUT_SUCCESS';
export const POST_LOGOUT_REQUEST: 'POST_LOGOUT_REQUEST' = 'POST_LOGOUT_REQUEST';
export const POST_LOGOUT_FAILED: 'POST_LOGOUT_FAILED' = 'POST_LOGOUT_FAILED';
